version: '3.3'

services:
  www:
    build: ./
    container_name: www_symfony
    restart: always
    ports:
      - '8000:8000'
    dns:
      - 8.8.8.8
    volumes:
      - ./:/var/www/
    command: "symfony server:start"
    networks:
      - rr-net

networks:
  rr-net:
    driver: bridge

volumes:
  db-data:
