version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./your-symfony-app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php