<?php

namespace ContainerT9Li3vx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3o_MB53Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3o.MB53' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3o.MB53'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\OfferController::import' => ['privates', '.service_locator.uBk8nC6', 'get_ServiceLocator_UBk8nC6Service', true],
            'App\\Controller\\OfferController::index' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController::list' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController::newOffer' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController::report' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController::test' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\OfferController:import' => ['privates', '.service_locator.uBk8nC6', 'get_ServiceLocator_UBk8nC6Service', true],
            'App\\Controller\\OfferController:index' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController:list' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController:newOffer' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController:report' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'App\\Controller\\OfferController:test' => ['privates', '.service_locator.pxonfHs', 'get_ServiceLocator_PxonfHsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\OfferController::import' => '?',
            'App\\Controller\\OfferController::index' => '?',
            'App\\Controller\\OfferController::list' => '?',
            'App\\Controller\\OfferController::newOffer' => '?',
            'App\\Controller\\OfferController::report' => '?',
            'App\\Controller\\OfferController::test' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\OfferController:import' => '?',
            'App\\Controller\\OfferController:index' => '?',
            'App\\Controller\\OfferController:list' => '?',
            'App\\Controller\\OfferController:newOffer' => '?',
            'App\\Controller\\OfferController:report' => '?',
            'App\\Controller\\OfferController:test' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
