<?php

namespace ContainerPuRYrHB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UBk8nC6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uBk8nC6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uBk8nC6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offerRepository' => ['privates', 'App\\Repository\\OfferRepository', 'getOfferRepositoryService', true],
            'poleemploiClient' => ['privates', 'App\\Service\\PoleemploiClient', 'getPoleemploiClientService', true],
        ], [
            'offerRepository' => 'App\\Repository\\OfferRepository',
            'poleemploiClient' => 'App\\Service\\PoleemploiClient',
        ]);
    }
}
