<?php

namespace ContainerPuRYrHB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPoleemploiClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PoleemploiClient' shared autowired service.
     *
     * @return \App\Service\PoleemploiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PoleemploiClient.php';

        return $container->privates['App\\Service\\PoleemploiClient'] = new \App\Service\PoleemploiClient(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), 'parameter("api")[\'poleemploi\'][\'client_id\']', 'parameter("api")[\'poleemploi\'][\'client_secret\']');
    }
}
