<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuRYrHB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuRYrHB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPuRYrHB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPuRYrHB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPuRYrHB\App_KernelDevDebugContainer([
    'container.build_hash' => 'PuRYrHB',
    'container.build_id' => 'dfa9cd64',
    'container.build_time' => 1695132070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuRYrHB');
