<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQQmoXPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQQmoXPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQQmoXPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQQmoXPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQQmoXPx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QQmoXPx',
    'container.build_id' => '87599231',
    'container.build_time' => 1695220298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQQmoXPx');
